# Sample Dockerfile

FROM mcr.microsoft.com/windows/servercore:ltsc2019-amd64
RUN dism /online /enable-feature /all /featurename:iis-webserver /NoRestart
RUN echo "Hello World - Dockerfile" > c:\inetpub\wwwroot\index.html
CMD [ "cmd" ]
